### ISSUE TITLE
[CDropdown] Not closed after click on CDropdownItem

### ISSUE THREAD

**Issue by darthf1** [coreui/coreui-vue#79] opened 2020-04-06 18:13 UTC
I have a dropdown on my Header component where the user can select a language:
```html
<c-dropdown toggler-text="Language">
  <c-dropdown-item :to="switchLocalePath('nl')">Dutch</c-dropdown-item>
  <c-dropdown-item :to="switchLocalePath('en')">English</c-dropdown-item>
</c-dropdown>
```

The `switchLocalePath` function is from [nuxt-i18n](https://github.com/nuxt-community/nuxt-i18n/blob/1bdf3207dddbf1dde66b2ea3b938a9d1411679fb/src/plugins/routing.js#L84) and returns a string, which is in this case the route with a different language. On click, the user is direct to another page, but the dropdown stays in place, opened. Below are the events emitted; the first one is from opening the dropdown and the second is after clicking on the dropdown item.

![image](https://user-images.githubusercontent.com/17253332/78589433-7981a100-7840-11ea-8554-35c2b05f2d7d.png)

Generated HTML:
```html
<div class="dropdown show">
    <button type="button" aria-expanded="true" aria-haspopup="true" class="btn dropdown-toggle">Language</button><!---->
    <div class="dropdown-menu show" style="margin: 0px; position: absolute; inset: 0px auto auto 0px; transform: translate(0px, 35px);" data-popper-placement="bottom-start">
        <a href="/" class="dropdown-item router-link-active" role="menuitem" target="_self">Dutch</a> 
        <a href="/en" class="dropdown-item router-link-exact-active router-link-active" role="menuitem" target="_self">English</a>
    </div>
</div>
```
```json
"@coreui/coreui": "3.0.0",
"@coreui/vue": "3.0.5",
```

The documentation mentions the usage of [router link props](https://coreui.io/vue/docs/3.0/components/Link.html#router-link-props). If i change `:to` to `:href` the dropdown closes, but then the page is fully refreshed (as is expected).

**Comment by woothu** [comment] 2020-04-08 07:14
Thank you for the report! The issue is fixed in 3.0.6 version.

**Closed by woothu** 2020-04-08 07:14 UTC
