### ISSUE TITLE
Sidebar Backdrop does not disappear on mobile

### ISSUE THREAD

**Issue by morganphilo** [coreui/coreui-vue#220] opened 2022-07-13 02:54 UTC
I am using Core UI Pro and have implemented the Sidebar in my app, but on mobile when I close the sidebar the backdrop remains.

Same issue exists on the documentation site:

Go to https://coreui.io/vue/docs/components/sidebar.html on mobile. 
Expand the menu
Tap the backdrop to hide the menu

Present on Android, Firefox and Chrome

**Comment by DGollings** [comment] 2022-07-21 14:34
same here, although it was said to be fixed in [v4.1.1](https://github.com/coreui/coreui/issues/254) but I'm not entirely sure if and how I could downgrade coreui and coreui/vue to that version

**Comment by mrholek** [comment] 2022-07-25 16:52
What version of @coreui/vue, and @coreui/coreui, do you use?

**Comment by morganphilo** [comment] 2022-07-25 21:10
@coreui/coreui 4.2.0
@coreui/vue 4.3.0

**Comment by morganphilo** [comment] 2022-07-25 21:13
I see it was fixed in v4.1.1 [here](https://github.com/coreui/coreui/issues/254#issuecomment-1059587545) as identified by @DGollings but I have that version and it persists.

**Comment by mrholek** [comment] 2022-07-28 18:57
@morganphilo on which mobile device and browser do you have this issue?

**Comment by morganphilo** [comment] 2022-07-28 19:06
Backdrop persists:
Pixel 6 Firefox and Chrome
Pixel 4XL Firefox and Chrome

Backdrop Works
IPhone Safari

**Comment by DGollings** [comment] 2022-07-28 19:08
Interesting, for me it's a pixel 6 pro with Firefox

**Comment by morganphilo** [comment] 2022-07-28 20:13
Ah interesting. I dusted off my old Galaxy S5 with Chrome and the backdrop goes away as usual.
Must be a Pixel issue.

**Comment by dang-cb** [comment] 2022-07-28 20:58
I experience the issue on an iPhone 13 Pro too, when in portrait mode. If the menu is expanded when in landscape mode, it clears as expected.

I wonder if certain media widths are causing this?
Dan

On 28 Jul 2022, at 21:14, Morgan Philo ***@***.***> wrote:

﻿

Ah interesting. I dusted off my old Galaxy S5 with Chrome and the backdrop goes away as expected.
Must be a Pixel issue.

**Comment by coderkoala** [comment] 2022-09-06 05:22
This hasn't been addressed at all, anything under 768px viewport gets stuck on the backdrop because the event's not firing on sidebar dismissal, thus the mutation never fires for changing the value responsible for maintaining visibility.

@mrholek easiest way to reproduce it is to simply use the mobile viewport in dev tools, activating the sidenav, then simply tap any item that pushes a different route view. The backdrop will now persist, and there's no way to take care of it.

I've jumped through all sorts of hoops to fix it, ranging from `visibility: hidden`, to manually triggering an update through mutations on each route push event through a plugin. Overall, it's been a major headache since coreui 4's arrived.

**Closed** 2022-11-12 14:24 UTC
Labels: no-issue-activity
