### ISSUE TITLE
Closing CModal leaves the page unclickable

### ISSUE THREAD

**Issue by silverskysoft** [coreui/coreui-vue#198] opened 2022-03-31 07:35 UTC
- Operating system and version: Windows 8.1
- Browser and version: Chrome 100, Firefox 98 
- This can be seen on https://coreui.io/vue/docs/components/modal.html 
Click on launch demo modal.
- Within our app it was using v4.2.0
After closing it we can't click anywhere on page. Expectation is we can click on other parts of the page.

We noticed after modal is closed, some CSS and HTML tags are left behind. If we remove them manually, the page becomes clickable again (see attached files)
[before_modal.txt](https://github.com/coreui/coreui-vue/files/8386928/before_modal.txt)
[after_modal_close.txt](https://github.com/coreui/coreui-vue/files/8386929/after_modal_close.txt)

This is issue is not seen on ReactJS demo and plainVanilla demo.
![GIF 3-31-2022 3-28-05 AM](https://user-images.githubusercontent.com/13212511/161002381-3751bb41-71d2-4d5c-92da-6e901deca108.gif)

**Comment by silverskysoft** [comment] 2022-04-04 15:03
@mrholek  - Is this the correct repo for the issue or should I open in coreUI repo?

**Comment by mrholek** [comment] 2022-04-04 15:20
@silverskysoft this repo is correct. I can't reproduce this on Mac, and Windows 11. I have to install Windows 8, I will try to fix it ASAP.

**Comment by tigerphc** [comment] 2022-04-22 06:44
Is it fixed? I also got the same problem.

**Comment by mrholek** [comment] 2022-04-27 08:27
@tigerphc It will be fixed in the next release this week. @silverskysoft thank you for your help with this issue.

**Comment by silverskysoftphab** [comment] 2022-05-10 05:21
Checked to be fixed in latest version.

**Closed** 2022-05-11 11:31 UTC
